---
- hosts: localhost
  tasks:
          - debug:
                  msg: "Starting deepthought"
          - include_role:
                  name: deepthought
          - include_role:
                  name: k8s-kubeadm-apt
          - debug:
                  msg: "Finsished deepthought"
  become: yes
  become_method: sudo
