---
- name: "{{ admin_user }}'s .kube dir"
  file:
          path: "/home/{{ admin_user }}/.kube"
          state: directory
          owner: "{{ admin_user }}"
          group: "{{ admin_user }}"
          mode: 0755

- name: copy kubeconfig
  copy:
          remote_src: yes
          src: /etc/kubernetes/admin.conf
          dest: /home/{{ admin_user }}/.kube/config
          owner: "{{ admin_user }}"
          group: "{{ admin_user }}"
          mode: 0600

- name: init helm
  shell: helm init
  environment:
          KUBECONFIG: /etc/kubernetes/admin.conf
  register: helm_init
- debug: var=helm_init.stdout_lines
