---
- name: install WeaveNet
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  environment:
          KUBECONFIG: /etc/kubernetes/admin.conf
  register: weavenet
- debug: var=weavenet.stdout_lines
